live_config_reload = true
import = [
   "~/.config/alacritty/font.toml",

# Themes
  # Catppuccin
  # "~/.config/alacritty/themes/catppuccin-mocha.toml",
  # Gruvbox
   "~/.config/alacritty/themes/themes/alacritty_0_12.toml"
]

